from dataclasses import dataclass
from typing import Protocol, runtime_checkable


@runtime_checkable
class ModelProvider(Protocol):
    provider_id: str
    display_name: str

    def generate(self, prompt: str, *, system_prompt: str = "", model_name: str = "") -> str:
        raise NotImplementedError


@dataclass
class MockModelProvider:
    provider_id: str = "mock-safe-local"
    display_name: str = "Mock Safe Local Provider"

    def generate(self, prompt: str, *, system_prompt: str = "", model_name: str = "") -> str:
        trimmed_prompt = " ".join(prompt.split())[:180]
        system_fragment = " ".join(system_prompt.split())[:100] if system_prompt else "default governed runtime"
        model_label = model_name or "mock-governed-small"
        return (
            f"Mock governed response generated by {model_label}. "
            f"System context: {system_fragment}. "
            f"Request summary: {trimmed_prompt}. "
            "No live provider call was made."
        )


class ProviderFactory:
    def get_provider(self, provider_id: str) -> ModelProvider:
        if provider_id == "mock-safe-local":
            return MockModelProvider()
        raise ValueError(f"Provider '{provider_id}' is registered as placeholder or unsupported in v0.6.")
